### ISSUE TITLE
Prefix in protocol

### ISSUE THREAD

**Issue by NoahPeeters** [upm-developers/upm-server#2]
_From @NoahPeeters on January 30, 2015 23:59_

We have to add something like a prefix to our protocol because it is important if the server gets a request from another server or from a client.

_Copied from original issue: upm-developers/upm#8_

**Comment by NoahPeeters** [comment]
_From @m-bra on January 31, 2015 13:27_

So the prefix says who is sending the message? Well, thats pretty deep in the implementation, but, if we need it, why not? :+1:

**Comment by m-bra** [comment]
So the prefix says who is sending the message? Well, thats pretty deep in the implementation, but, if we need it, why not? :+1:

**Comment by m-bra** [comment]
Wait but why? I think the server knows where a received message comes from? So the sender does not have to say who he is?

**Comment by m-bra** [comment]
This is actually the same issue as #1 , continuing there
