### ISSUE TITLE
sync server list with all servers *automatically*?

### ISSUE THREAD

**Issue by m-bra** [upm-developers/upm-server#4]
What if the server maintainer does not want that? Can't he set all server lists on all servers manually, or if _does_ wanna do it, have a command for it?

**Comment by m-bra** [comment]
Or will the maintainer always want to have the servers automatically sync their server lists?

**Comment by NoahPeeters** [comment]
Ok. Then two servers only sync the packages and not the other servers.
(That idea is still from the old model. Thats why I don't thought about that again)

**Comment by m-bra** [comment]
Okay
